### PR TITLE
Sessions bugfix

### LINKED ISSUE #351: Error when trying to log in with non existing user
**Steps to reproduce:**

- go to sign in
- try to log in with a non existing user

**expected behaviour**
- the user doesn't exist

**current behaviour**
- raises an error (undefined method `encrypted_password' for nil:NilClass)

this is due to the quick fix we developed for those user without encrypted passwords. it can probably be quickly fixed in the sessions_controller with a new if clause.

### PR DESCRIPTION
**Pull request by mauditecandela**
Fixes a session bug so when a User without an existing account tries to sign in, they will be redirected to the sign up page.

Closes #351

### CODE REVIEW

File: app/controllers/sessions_controller.rb [hunk 1]
```diff
@@ -1,8 +1,12 @@
 class SessionsController < Clearance::SessionsController
 
   def create
-    if params[:session][:password] && User.find_by(email: params[:session][:email]).encrypted_password == 'x'
-      redirect_to  new_password_path, flash: { :info => "Due to a security update from our side we kindly ask you to reset your password." }
+    if User.find_by(email:params[:session][:email]).nil?
+      redirect_to sign_up_path, flash: { :alert => "Account not found, please sign up"}
+
+    elsif User.find_by(email: params[:session][:email]).encrypted_password == 'x'
+      pp params
```
Comment (guainumbi) [inline app/controllers/sessions_controller.rb]: we should take out "pp params" :)

File: app/controllers/sessions_controller.rb [hunk 2]
```diff
@@ -1,8 +1,12 @@
 class SessionsController < Clearance::SessionsController
 
   def create
-    if params[:session][:password] && User.find_by(email: params[:session][:email]).encrypted_password == 'x'
-      redirect_to  new_password_path, flash: { :info => "Due to a security update from our side we kindly ask you to reset your password." }
+    if User.find_by(email:params[:session][:email]).nil?
+      redirect_to sign_up_path, flash: { :alert => "Account not found, please sign up"}
```
Comment (guainumbi) [inline app/controllers/sessions_controller.rb]: maybe: "Account not found, please register first" (i think it makes clearer whats happening, so people dont confuse sign up with sign in)

Comment (guainumbi) [reply app/controllers/sessions_controller.rb]: what happens to the case if someone enters no password?
